plugins {
    id 'com.android.application'
}

android {
    namespace 'xyz.filime.app'
    compileSdk 35

    defaultConfig {
        applicationId 'xyz.filime.app'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        debug {
            buildConfigField(
                'String',
                'REWARDED_AD_UNIT_ID',
                '"ca-app-pub-3940256099942544/5224354917"'
            )
        }

        release {
            minifyEnabled false

            buildConfigField(
                'String',
                'REWARDED_AD_UNIT_ID',
                '"ca-app-pub-4389499756069615/6888816246"'
            )

            proguardFiles(
                getDefaultProguardFile(
                    'proguard-android-optimize.txt'
                ),
                'proguard-rules.pro'
            )
        }
    }

    buildFeatures {
        buildConfig true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.core:core:1.15.0'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.webkit:webkit:1.12.1'

    implementation 'com.google.android.gms:play-services-ads:23.6.0'
}
